export * from './articles.service';
import {ArticlesApiService} from './articles.service';
import {AuthApiService} from './auth.service';
import {CommentsApiService} from './comments.service';
import {ContributeSessionsApiService} from './contribute-sessions.service';
import {ContributionsApiService} from './contributions.service';
import {FacultiesApiService} from './faculties.service';
import {StatisticsApiService} from './statistics.service';
import {StorageApiService} from './storage.service';
import {SystemDataApiService} from './system-data.service';
import {UsersApiService} from './users.service';

export * from './auth.service';
export * from './comments.service';
export * from './contribute-sessions.service';
export * from './contributions.service';
export * from './faculties.service';
export * from './statistics.service';
export * from './storage.service';
export * from './system-data.service';
export * from './users.service';
export const APIS = [ArticlesApiService, AuthApiService, CommentsApiService, ContributeSessionsApiService, ContributionsApiService, FacultiesApiService, StatisticsApiService, StorageApiService, SystemDataApiService, UsersApiService];
