export * from './articles.service';
import { ArticlesApiService } from './articles.service';
export * from './auth.service';
import { AuthApiService } from './auth.service';
export * from './comments.service';
import { CommentsApiService } from './comments.service';
export * from './contribute-sessions.service';
import { ContributeSessionsApiService } from './contribute-sessions.service';
export * from './contributions.service';
import { ContributionsApiService } from './contributions.service';
export * from './faculties.service';
import { FacultiesApiService } from './faculties.service';
export * from './storage.service';
import { StorageApiService } from './storage.service';
export * from './system-data.service';
import { SystemDataApiService } from './system-data.service';
export * from './users.service';
import { UsersApiService } from './users.service';
export const APIS = [ArticlesApiService, AuthApiService, CommentsApiService, ContributeSessionsApiService, ContributionsApiService, FacultiesApiService, StorageApiService, SystemDataApiService, UsersApiService];
