/**
 * 123
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleVersionRes } from './article-version-res';


export interface ArticleArticleRes { 
    createdAt?: string;
    id?: number;
    updatedAt?: string;
    versions?: Array<ArticleVersionRes>;
}

