/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArticleVersionRes } from './articleVersionRes';


export interface ArticleArticleRes { 
    createdAt?: string;
    description?: string;
    id?: number;
    title?: string;
    updatedAt?: string;
    versions?: Array<ArticleVersionRes>;
}
