/**
 * 123
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserUserResponse } from './user-user-response';


export interface CommentCommentRes { 
    content?: string;
    createdAt?: string;
    edited?: boolean;
    id?: string;
    updatedAt?: string;
    user?: UserUserResponse;
}

