/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContributionUserRes } from './contributionUserRes';


export interface ContributionContributionRes { 
    articleId?: number;
    contributeSessionId?: number;
    createdAt?: string;
    id?: number;
    status?: string;
    updatedAt?: string;
    user?: ContributionUserRes;
}
