/**
 * 123
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContributionUserRes } from './contribution-user-res';


export interface ContributionContributionRes { 
    articleId?: number;
    contributeSessionId?: number;
    createdAt?: string;
    description?: string;
    id?: number;
    status?: string;
    title?: string;
    updatedAt?: string;
    user?: ContributionUserRes;
}

