/**
 * 123
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FacultyFacultyResponse } from './faculty-faculty-response';


export interface FacultyPaginateComposition { 
    currentPage?: number;
    data?: Array<FacultyFacultyResponse>;
    lastPage?: number;
    perPage?: number;
    total?: number;
}

