/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommentCommentRes } from './commentCommentRes';
import { CommonCursorResponse } from './commonCursorResponse';


export interface InlineResponse200 { 
    commonCursorResponse?: CommonCursorResponse;
    data?: Array<CommentCommentRes>;
}
