/**
 * 123
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SystemdataDataRes {
  key?: string;
  type?: SystemdataDataRes.TypeEnum;
  updatedAt?: string;
  value?: string;
}

export namespace SystemdataDataRes {
  export type TypeEnum = 'document' | 'int' | 'string';
  export const TypeEnum = {
    Document: 'document' as TypeEnum,
    Int: 'int' as TypeEnum,
    String: 'string' as TypeEnum
  };
}


