/**
 * 123
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserUserUpdateReq {
  email?: string;
  facultyId?: number;
  name?: string;
  password?: string;
  role?: string;
  status?: UserUserUpdateReq.StatusEnum;
}

export namespace UserUserUpdateReq {
  export type StatusEnum = 'active' | 'disable';
  export const StatusEnum = {
    Active: 'active' as StatusEnum,
    Disable: 'disable' as StatusEnum
  };
}


