/**
 * 123
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserUserCreateReq { 
    email?: string;
    facultyId?: number;
    name?: string;
    password?: string;
    role?: UserUserCreateReq.RoleEnum;
    status?: string;
}
export namespace UserUserCreateReq {
    export type RoleEnum = 'admin' | 'marketing_manager' | 'marketing_coordinator' | 'student' | 'guest';
    export const RoleEnum = {
        Admin: 'admin' as RoleEnum,
        MarketingManager: 'marketing_manager' as RoleEnum,
        MarketingCoordinator: 'marketing_coordinator' as RoleEnum,
        Student: 'student' as RoleEnum,
        Guest: 'guest' as RoleEnum
    };
}


